# Generated by Django 5.0.3 on 2024-03-24 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLastIDs',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=255)),
                ('lastID', models.CharField(max_length=255)),
                ('lastRun', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
