# Generated by Django 5.0.3 on 2024-03-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0002_storeytdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeytdata',
            name='descriptionYT',
            field=models.TextField(),
        ),
    ]
