# Generated by Django 5.0.3 on 2024-03-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0003_alter_storeytdata_descriptionyt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeytdata',
            name='descriptionYT',
            field=models.TextField(blank=True),
        ),
    ]
