# Generated by Django 5.0.3 on 2024-03-28 12:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0006_alter_storeytdata_descriptionyt'),
    ]

    operations = [
        migrations.CreateModel(
            name='storeData',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('storeTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataURL', models.CharField(max_length=255)),
                ('publishDateYT', models.DateTimeField()),
                ('videoIdYT', models.CharField(max_length=255)),
                ('videoTitleYT', models.CharField(max_length=255)),
                ('viewsYT', models.CharField(max_length=255)),
                ('thumbnailYT', models.CharField(max_length=255)),
                ('descriptionYT', models.TextField(blank=True)),
                ('platform', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='storeYTData',
        ),
    ]
