# Generated by Django 5.0.3 on 2024-03-28 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0008_storedata_channelnameyt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedata',
            name='descriptionYT',
        ),
    ]
