# Generated by Django 5.0.3 on 2024-04-08 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0010_banneryt'),
    ]

    operations = [
        migrations.CreateModel(
            name='dpInsta',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('storeTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataURL', models.TextField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
