# Generated by Django 5.0.3 on 2024-04-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0011_dpinsta'),
    ]

    operations = [
        migrations.AddField(
            model_name='banneryt',
            name='name',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
