# Generated by Django 5.0.3 on 2024-04-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0012_banneryt_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='banneryt',
            name='subsCount',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
