# Generated by Django 5.0.3 on 2024-04-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0013_banneryt_subscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banneryt',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dpinsta',
            name='name',
        ),
    ]
