# Generated by Django 5.0.3 on 2024-04-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0014_remove_banneryt_name_remove_dpinsta_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpinsta',
            name='followerCount',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
