# Generated by Django 5.0.3 on 2024-04-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0016_twitterdp_storedata_instathumbnailurl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaURL', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='storedata',
            name='mediaLinks',
        ),
        migrations.AddField(
            model_name='storedata',
            name='mediaLinks',
            field=models.ManyToManyField(to='joycaHome.medialinks'),
        ),
    ]
