# Generated by Django 5.0.3 on 2024-04-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0017_medialinks_remove_storedata_medialinks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedata',
            name='mediaLinks',
        ),
    ]
