# Generated by Django 5.0.3 on 2024-04-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0018_remove_storedata_medialinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedata',
            name='mediaLinks',
            field=models.URLField(default='1'),
            preserve_default=False,
        ),
    ]
