# Generated by Django 5.0.3 on 2024-04-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0019_storedata_medialinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedata',
            name='mediaLinks',
            field=models.JSONField(),
        ),
    ]
