# Generated by Django 5.0.3 on 2024-04-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0021_storedata_mediaurl_storedata_twitterthumbnailurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedata',
            name='tweetText',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
