# Generated by Django 5.0.3 on 2024-04-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0022_storedata_tweettext'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedata',
            name='likes',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
