# Generated by Django 5.0.3 on 2024-04-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0023_storedata_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storedata',
            old_name='isSingle',
            new_name='instaIsSingle',
        ),
        migrations.RenameField(
            model_name='storedata',
            old_name='isVideo',
            new_name='instaIsVideo',
        ),
        migrations.RenameField(
            model_name='storedata',
            old_name='mediaLinks',
            new_name='instaMediaLinks',
        ),
        migrations.RenameField(
            model_name='storedata',
            old_name='postID',
            new_name='instaPostID',
        ),
        migrations.RenameField(
            model_name='storedata',
            old_name='videoURL',
            new_name='instaVideoURL',
        ),
        migrations.RenameField(
            model_name='storedata',
            old_name='likes',
            new_name='twitterLikes',
        ),
        migrations.RenameField(
            model_name='storedata',
            old_name='mediaURL',
            new_name='twitterMediaURL',
        ),
        migrations.AddField(
            model_name='storedata',
            name='twitterPostID',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storedata',
            name='twitterSsVideo',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
