# Generated by Django 5.0.3 on 2024-04-14 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0024_rename_issingle_storedata_instaissingle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storedata',
            old_name='twitterSsVideo',
            new_name='twitterIsVideo',
        ),
    ]
