# Generated by Django 5.0.3 on 2024-04-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0026_storedata_tweetlink_alter_storedata_twitterlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedata',
            name='instaMediaLinks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
