# Generated by Django 5.0.3 on 2024-04-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0027_alter_storedata_instamedialinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedata',
            name='instaDesc',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
