# Generated by Django 5.0.3 on 2024-04-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0028_storedata_instadesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterdp',
            name='dpURL',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
