# Generated by Django 5.0.3 on 2024-04-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0029_twitterdp_dpurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedata',
            name='instaLikes',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
