# Generated by Django 5.0.3 on 2024-04-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0030_storedata_instalikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedata',
            name='instaPostLink',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
