# Generated by Django 5.0.3 on 2024-04-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0031_storedata_instapostlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedata',
            name='instaVideoURL',
            field=models.TextField(blank=True, null=True),
        ),
    ]
