# Generated by Django 5.0.3 on 2024-04-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0033_remove_storedata_twitterpostid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedata',
            name='twitterPostID',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
