# Generated by Django 5.0.3 on 2024-05-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joycaHome', '0034_storedata_twitterpostid'),
    ]

    operations = [
        migrations.CreateModel(
            name='instagramAccessToken',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('accessToken', models.TextField()),
            ],
        ),
    ]
