# Generated by Django 5.0.3 on 2024-05-07 08:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bannerYT',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('storeTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataURL', models.TextField()),
                ('dpURL', models.TextField()),
                ('subsCount', models.CharField(max_length=255)),
                ('ytHandle', models.CharField(max_length=255)),
                ('ytLink', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='domain',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='dpInsta',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('storeTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataURL', models.TextField()),
                ('dpURL', models.TextField()),
                ('followerCount', models.CharField(max_length=255)),
                ('instaHandle', models.CharField(max_length=255)),
                ('instaLink', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='instagramAccessToken',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('accessToken', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaURL', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='storeData',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('storeTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('publishDateYT', models.DateTimeField()),
                ('platform', models.CharField(max_length=255)),
                ('channelNameYT', models.CharField(max_length=255)),
                ('dataURL', models.CharField(max_length=255)),
                ('videoIdYT', models.CharField(max_length=255)),
                ('videoTitleYT', models.CharField(max_length=255)),
                ('viewsYT', models.CharField(max_length=255)),
                ('thumbnailYT', models.CharField(max_length=255)),
                ('instaThumbnailURL', models.TextField()),
                ('instaIsVideo', models.CharField(max_length=255)),
                ('instaVideoURL', models.TextField(blank=True, null=True)),
                ('instaDesc', models.TextField()),
                ('instaPostLink', models.TextField()),
                ('instaLikes', models.TextField()),
                ('instaPostID', models.CharField(max_length=255)),
                ('instaIsSingle', models.CharField(max_length=255)),
                ('instaMediaLinks', models.JSONField(blank=True, null=True)),
                ('tweetText', models.TextField()),
                ('twitterLikes', models.CharField(max_length=255)),
                ('tweetLink', models.TextField()),
                ('twitterIsVideo', models.CharField(max_length=255)),
                ('twitterMediaURL', models.TextField()),
                ('twitterPostID', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StoreLastIDs',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=255)),
                ('lastID', models.CharField(max_length=255)),
                ('lastRun', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='twitterDP',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('storeTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataURL', models.TextField()),
                ('dpURL', models.TextField()),
                ('followerCount', models.CharField(max_length=255)),
                ('twitterHandle', models.CharField(max_length=255)),
                ('twitterLink', models.TextField()),
            ],
        ),
    ]
