# Generated by Django 4.1.5 on 2023-08-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResources',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('news', models.TextField()),
                ('link', models.CharField(blank=True, max_length=130, null=True)),
            ],
            options={
                'verbose_name': 'LatestNews',
                'verbose_name_plural': 'Latest News',
            },
        ),
    ]
