# Generated by Django 4.1.5 on 2023-08-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0004_resourcespercategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResourcesPerCategory',
            new_name='ResourcesByCategory',
        ),
        migrations.AlterModelOptions(
            name='resourcesbycategory',
            options={'verbose_name': 'Resources By Category', 'verbose_name_plural': 'Resources By Category'},
        ),
    ]
