# Generated by Django 4.1.5 on 2023-08-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_rename_resourcespercategory_resourcesbycategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcecategory',
            old_name='imageLink',
            new_name='image_Link',
        ),
        migrations.RenameField(
            model_name='resourcesbycategory',
            old_name='name',
            new_name='link_To',
        ),
        migrations.RenameField(
            model_name='resourcesbycategory',
            old_name='resourceLink',
            new_name='resource_Link',
        ),
        migrations.RenameField(
            model_name='resourcesbycategory',
            old_name='resourceSummary',
            new_name='resource_Thumbnail',
        ),
        migrations.RemoveField(
            model_name='resourcesbycategory',
            name='resourceThumbnail',
        ),
        migrations.AddField(
            model_name='resourcesbycategory',
            name='resource_Summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
