# Generated by Django 4.1.5 on 2023-08-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0006_rename_imagelink_resourcecategory_image_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcecategory',
            options={'verbose_name': 'Exam', 'verbose_name_plural': 'Exam'},
        ),
        migrations.RenameField(
            model_name='resourcecategory',
            old_name='name',
            new_name='category',
        ),
    ]
