# Generated by Django 4.1.5 on 2023-08-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0007_alter_resourcecategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcesbycategory',
            old_name='link_To',
            new_name='category',
        ),
    ]
