# Generated by Django 4.1.5 on 2023-08-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0008_rename_link_to_resourcesbycategory_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryresources',
            options={'verbose_name': 'Exam Name', 'verbose_name_plural': 'Exam Name'},
        ),
        migrations.AlterModelOptions(
            name='resourcesbycategory',
            options={'verbose_name': 'Resources By Exam', 'verbose_name_plural': 'Resources By Exam'},
        ),
        migrations.RenameField(
            model_name='resourcecategory',
            old_name='category',
            new_name='exam_Name',
        ),
        migrations.RenameField(
            model_name='resourcesbycategory',
            old_name='category',
            new_name='exam_Name',
        ),
    ]
