# Generated by Django 4.1.5 on 2023-08-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0009_alter_categoryresources_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResourceCategory',
            new_name='Exam',
        ),
        migrations.RenameModel(
            old_name='CategoryResources',
            new_name='ExamName',
        ),
    ]
