# Generated by Django 4.1.5 on 2023-08-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0010_rename_resourcecategory_exam_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResourcesByCategory',
            new_name='ResourcesByExam',
        ),
    ]
