# Generated by Django 4.1.5 on 2023-08-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0011_rename_resourcesbycategory_resourcesbyexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcesbyexam',
            name='resource_Name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcesbyexam',
            name='resource_Link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resourcesbyexam',
            name='resource_Thumbnail',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
