# Generated by Django 4.1.5 on 2023-08-25 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0012_resourcesbyexam_resource_name_alter_latestnews_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_Name',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='resourcesbyexam',
            name='exam_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApp.exam'),
        ),
        migrations.DeleteModel(
            name='ExamName',
        ),
    ]
