# Generated by Django 4.1.5 on 2023-08-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0013_alter_exam_exam_name_alter_resourcesbyexam_exam_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestnews',
            name='link',
        ),
        migrations.AddField(
            model_name='latestnews',
            name='link_Optional',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
