# Generated by Django 4.1.5 on 2023-08-27 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0014_remove_latestnews_link_latestnews_link_optional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latestnews',
            old_name='link_Optional',
            new_name='link',
        ),
    ]
