# Generated by Django 4.1.5 on 2023-08-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0015_rename_link_optional_latestnews_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
