# Generated by Django 4.1.5 on 2023-08-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0016_exam_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='image',
            field=models.ImageField(upload_to='uploaded-images'),
        ),
    ]
