# Generated by Django 4.1.5 on 2023-08-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0019_remove_exam_image_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='image',
            new_name='image_Link',
        ),
    ]
