# Generated by Django 4.1.5 on 2023-09-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0020_rename_image_exam_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcesbyexam',
            name='resource_Summary',
        ),
    ]
