# Generated by Django 4.1.5 on 2023-09-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0021_remove_resourcesbyexam_resource_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemsOfTheWeek',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('questionLink', models.CharField(max_length=255)),
                ('answerLink', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_Thumbnail', models.ImageField(upload_to='static/potw')),
            ],
            options={
                'verbose_name': 'Problem Of The Week',
                'verbose_name_plural': 'Problem Of The Weeks',
            },
        ),
    ]
