# Generated by Django 4.1.5 on 2023-09-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0022_problemsoftheweek'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemsoftheweek',
            options={'verbose_name': 'Problem Of The Week', 'verbose_name_plural': 'Problem Of The Week'},
        ),
    ]
