# Generated by Django 4.1.5 on 2023-09-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0023_alter_problemsoftheweek_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemsOfTheWeekAnnouncement',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('announcement', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Problem Of The Week Announcement',
                'verbose_name_plural': 'Problem Of The Week Announcement',
            },
        ),
    ]
