# Generated by Django 4.2.5 on 2023-09-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0024_problemsoftheweekannouncement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='image_Link',
            field=models.ImageField(upload_to='uploaded-images/'),
        ),
        migrations.AlterField(
            model_name='problemsoftheweek',
            name='resource_Thumbnail',
            field=models.ImageField(upload_to='potw/'),
        ),
        migrations.AlterField(
            model_name='resourcesbyexam',
            name='resource_Thumbnail',
            field=models.ImageField(upload_to='resource-thumbnail/'),
        ),
    ]
