# Generated by Django 4.2.5 on 2023-09-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0025_alter_exam_image_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='image_Link',
            field=models.ImageField(upload_to='media/uploaded-images/'),
        ),
        migrations.AlterField(
            model_name='problemsoftheweek',
            name='resource_Thumbnail',
            field=models.ImageField(upload_to='media/potw/'),
        ),
        migrations.AlterField(
            model_name='resourcesbyexam',
            name='resource_Thumbnail',
            field=models.ImageField(upload_to='media/resource-thumbnail/'),
        ),
    ]
